#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=01

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh "/sbin/s12-pro-signal"
    procd_close_instance
}

stop_service() {
    killall -q s12-pro-signal
}
